Vs add locations
cybergizer/nicher pull request #26
Opened 2018-08-08 07:26 UTC by Vadser

2018-08-10 07:06 UTC, Sergyenko requested changes

2018-08-10 07:06 UTC, Sergyenko commented on app/controllers/niches_controller.rb
> +    parent = current_user.niches.find_by(id: niche_params[:parent])
What if current_user.niches returns 'nil'?

2018-08-10 07:06 UTC, Sergyenko commented on app/controllers/niches_controller.rb
> +    @niche = current_user.niches.create(name: niche_params[:name], parent: parent)
DRY 'current_user.niches'

2018-08-10 07:06 UTC, Sergyenko commented on app/controllers/niches_controller.rb
> +      redirect_to niche_url(@niche)
would that be more elegant 'redirect_to @niche'

2018-08-10 07:06 UTC, Sergyenko commented on app/controllers/niches_controller.rb
> +    parent = current_user.niches.find_by(id: niche_params[:parent])
DRY current_user.niches.find_by

2018-08-10 07:06 UTC, Sergyenko commented on app/controllers/niches_controller.rb
> +      redirect_to niche_url(@niche)
same as above

2018-08-10 07:06 UTC, Sergyenko commented on app/controllers/niches_controller.rb
> +  def set_niche
Think about the creating helper for this code. As it's the same as here:
https://github.com/cybergizer/nicher/pull/28/files#diff-8cf35630782fed586aedb0f80d9fefbeR41

2018-08-10 07:06 UTC, Sergyenko commented on app/models/niche.rb
> +    niche.save
What if save is unsuccessful?

2018-08-10 07:06 UTC, Sergyenko commented on app/models/niche.rb
> +    niche.save
What if save is unsuccessful?

2018-08-10 07:06 UTC, Sergyenko commented on app/models/niche.rb
> +    niche.destroy
What if destroy is unsuccessful?

2018-08-10 07:06 UTC, Sergyenko commented on app/models/user.rb
> +  has_many :niches, class_name: 'Niche', dependent: :delete_all
Do you still need to specify "class_name: 'Niche'"?

2018-08-10 07:06 UTC, Sergyenko commented on app/views/niches/show.html.slim
> +    - @niche.items.each do |item|
What if @niche.items returns nil?

2018-08-10 07:06 UTC, Sergyenko commented on app/views/niches/show.html.slim
> +      - @niche.children.each do |niche|
What if @niche.children returns nil?

2018-08-10 07:06 UTC, Sergyenko commented on app/views/shared/_menu.html.slim
> +      a href="/niches"
Use rails URL helpers

2018-08-10 14:15 UTC, anatoliliotych requested changes

2018-08-10 14:15 UTC, anatoliliotych commented on spec/controllers/niches_controller_spec.rb
> +      niche.reload
check that new attributes were applied

2018-08-13 12:46 UTC, Sergyenko submitted a review, later dismissed

2018-08-13 15:54 UTC, anatoliliotych reviewed
app/views/.DS_Store - should be ignored

2018-08-13 15:54 UTC, anatoliliotych commented on app/assets/stylesheets/login.scss
> +
why it is here?

2018-08-13 15:54 UTC, anatoliliotych commented on app/controllers/niches_controller.rb
> +    @niche = current_user.niches.create
it's kind of dangerous to create objects on form opening, do you remove them if user doesn't save form?

2018-08-13 15:54 UTC, anatoliliotych commented on app/models/niche.rb
> +  has_many :items, dependent: :delete_all
try to keep these sections as separate blocks via empty lines

2018-08-13 15:54 UTC, anatoliliotych commented on app/models/niche.rb
> +    niche = our_niche.descendants.find_by(id: niche.id)
find_by can return nil, so you'll call parent and save on nil.

2018-08-13 15:54 UTC, anatoliliotych commented on app/models/niche.rb
> +    niche = our_niche.descendants.find_by(id: niche.id)
I'd remove this method, it's kind of strange to remove one niche through another.

2018-08-13 16:00 UTC, anatoliliotych requested changes
why this file is removed `config/database.yml.example`?

2018-08-13 16:00 UTC, anatoliliotych commented on spec/controllers/niches_controller_spec.rb
> +  let(:invalid_attributes) { attributes_for(:invalid_niche).merge(user_id: 1) }
this is wrong way to make invalid params, what if user_id=1 will exist?

2018-08-13 16:00 UTC, anatoliliotych commented on spec/controllers/niches_controller_spec.rb
> +    it "redirects to new view page" do
invalid example name! should be about valid response

2018-08-13 16:00 UTC, anatoliliotych commented on spec/controllers/niches_controller_spec.rb
> +    it "renders the @edit view" do
@edit?

2018-08-13 16:00 UTC, anatoliliotych commented on spec/factories/user.rb
> +  factory :user, aliases: %i[author] do
what does it mean author?

2018-08-13 18:20 UTC, anatoliliotych commented
![lgtm-ship-it](https://user-images.githubusercontent.com/2376239/44050076-8e2c0e7e-9f3e-11e8-9dd0-acac4c8460bd.jpg)

2018-08-13 18:20 UTC, anatoliliotych approved these changes

2018-08-13 18:20 UTC, merged