WIP: As add categories
cybergizer/nicher pull request #28
Opened 2018-08-08 08:48 UTC by SashaShostyr

2018-08-10 06:50 UTC, Sergyenko requested changes

2018-08-10 06:50 UTC, Sergyenko commented on app/views/items/index.html.slim
> +        td= item.category&.name
item.category&.name - typo?

2018-08-10 06:57 UTC, Sergyenko submitted a review, later dismissed

2018-08-10 06:57 UTC, Sergyenko commented on app/controllers/categories_controller.rb
> +
Think about the creating helper for this code. As it's the same as here:
https://github.com/cybergizer/nicher/pull/26/files#diff-dbc6fdbfa3706e8655ca693ae7639d6bR54

2018-08-10 07:05 UTC, SashaShostyr commented on app/views/items/index.html.slim
> +        td= item.category&.name
no, & - safe navigation operator

2018-08-10 18:19 UTC, anatoliliotych requested changes

2018-08-10 18:19 UTC, anatoliliotych commented on app/controllers/items_controller.rb
> +    params.require(:item).permit(:title, :description, :category_id)
be sure that you will follow the same approach @Vadser is doing

2018-08-10 18:19 UTC, anatoliliotych commented on spec/controllers/categories_controller_spec.rb
> +  let(:invalid_attributes) {
why it's not valid?

2018-08-10 18:19 UTC, anatoliliotych commented on spec/controllers/categories_controller_spec.rb
> +      Category.create! valid_attributes
please, talk to @Vadser about creation of objects.

2018-08-12 18:22 UTC, anatoliliotych requested changes

2018-08-12 18:22 UTC, anatoliliotych commented on app/helpers/categories_helper.rb
> +module CategoriesHelper
remove helper it's empty

2018-08-12 18:22 UTC, anatoliliotych commented on app/helpers/application_helper.rb
> +  def set_resource
move all methods to concern in a separate PR.

2018-08-12 18:22 UTC, anatoliliotych commented on app/views/items/_form.html.slim
> +    = form.collection_select(:category_id, Category.all, :id, :name, :include_blank => "Please select")
`Category.all` - will show you categories from other users!

2018-08-12 18:22 UTC, anatoliliotych commented on spec/controllers/categories_controller_spec.rb
> +  describe 'GET #index' do
add test for correct route

2018-08-12 18:22 UTC, anatoliliotych commented on spec/controllers/categories_controller_spec.rb
> +  describe 'GET #index' do
add this for all actions!

2018-08-12 18:22 UTC, anatoliliotych commented on spec/controllers/categories_controller_spec.rb
> +        expect(response).to redirect_to(Category.last)
bad approach! check that you are redirected exactly to created category

2018-08-12 18:22 UTC, anatoliliotych commented on spec/controllers/categories_controller_spec.rb
> +        expect(response).to render_template :edit
check that flash message is shown for all cases!

2018-08-12 18:22 UTC, anatoliliotych commented on spec/models/item_spec.rb
> +  let(:user) { User.create(email: 'test@gmail.com', password: 'password', password_confirmation: 'password') }
use FactoryBot!

2018-08-12 18:22 UTC, anatoliliotych commented on spec/spec_helper.rb
> +    expectations.syntax = [:should, :expect]
use only expects!

2018-08-13 16:21 UTC, anatoliliotych requested changes

2018-08-13 16:21 UTC, anatoliliotych commented on app/controllers/categories_controller.rb
> +    @category = current_user.categories.create
you shouldn't create db record on page opening!

2018-08-13 16:21 UTC, anatoliliotych commented on spec/controllers/categories_controller_spec.rb
> +        expect(category.errors).to be_present
not exact check, you can get validation error not related to what you've meant, so be more specific in tests.

2018-08-13 20:26 UTC, anatoliliotych requested changes

2018-08-13 20:26 UTC, anatoliliotych commented on app/controllers/categories_controller.rb
> +    if @category.save
replace with valid? or remove create and use new

2018-08-13 20:26 UTC, anatoliliotych commented on app/models/item.rb
> +
use the same sections together

2018-08-14 12:28 UTC, anatoliliotych approved these changes

2018-08-14 12:28 UTC, anatoliliotych commented
lgtm

2018-08-14 12:36 UTC, merged