Add history to items
cybergizer/nicher pull request #49
Opened 2018-08-15 06:41 UTC by idealasgas

2018-08-15 10:05 UTC, Vadser approved these changes
LGTM

2018-08-15 10:26 UTC, reedzyy approved these changes

2018-08-15 16:35 UTC, idealasgas commented
**need code review**

2018-08-15 20:43 UTC, anatoliliotych commented
remove this commit! `Update to the latest dev` before I start review!
This means that you've made something wrong during rebase. I need really careful work with git!

2018-08-16 11:24 UTC, anatoliliotych requested changes
Needs demo!

2018-08-16 11:24 UTC, anatoliliotych commented on app/views/items/show.html.slim
> +- unless @item.created_at == @item.updated_at
you can check version number instead of such check

2018-08-16 11:24 UTC, anatoliliotych commented on app/views/items/show.html.slim
> +                    td somewhere
what does it mean?

2018-08-16 11:24 UTC, anatoliliotych commented on app/views/items/show.html.slim
> +                    td= Niche.all.find {|niche| niche.id == v.niche_id}.name
why do we have this here?

2018-08-16 11:24 UTC, anatoliliotych commented on app/views/items/show.html.slim
> +                  td= User.all.find {|user| user.id == v.user_id}.first_name
bad approach to do this in view

2018-08-17 14:56 UTC, idealasgas commented on app/views/items/show.html.slim
> +                    td somewhere
default value if niche is not set

2018-08-19 17:39 UTC, closed without merging