Add tests
cybergizer/nicher pull request #50
Opened 2018-08-15 14:54 UTC by SashaShostyr

2018-08-15 15:10 UTC, idealasgas approved these changes

2018-08-15 15:23 UTC, reedzyy approved these changes

2018-08-15 16:34 UTC, SashaShostyr commented
Need code review!

2018-08-15 20:42 UTC, anatoliliotych requested changes

2018-08-15 20:42 UTC, anatoliliotych commented on spec/controllers/items_controller_spec.rb
> +        expect(item.errors.messages[:title]).to be_present
what message?

2018-08-15 20:42 UTC, anatoliliotych commented on spec/controllers/items_controller_spec.rb
> +        expect(item.errors.messages[:title]).to be_present
what message?

2018-08-15 20:42 UTC, anatoliliotych commented on spec/controllers/sessions_controller_spec.rb
> +  controller do
could it be moved to some support class? doesn't look like something we need in this file

2018-08-16 13:47 UTC, anatoliliotych approved these changes
LGTM

2018-08-16 13:47 UTC, merged