Add ability to upload avatars
cybergizer/nicher pull request #54
Opened 2018-08-17 07:59 UTC by leshkacore

2018-08-17 09:59 UTC, SashaShostyr approved these changes

2018-08-17 10:01 UTC, idealasgas approved these changes

2018-08-17 11:36 UTC, anatoliliotych requested changes

2018-08-17 11:36 UTC, anatoliliotych commented on app/views/shared/_user_info.html.slim
> +    = image_tag(current_user.user_profile.avatar.icon.url, alt: 'Image') if current_user.user_profile.avatar?
where is default avatar? can you move all this magic to model?

2018-08-17 11:36 UTC, anatoliliotych commented on spec/uploaders/avatar_uploader_spec.rb
> +    expect(uploader.size).to be <=1000000 # bytes
what about style?

2018-08-20 18:48 UTC, anatoliliotych requested changes

2018-08-20 18:48 UTC, anatoliliotych commented on app/uploaders/avatar_uploader.rb
> +  # Provide a default URL as a default if there hasn't been a file uploaded:
remove all unneeded comments

2018-08-20 18:48 UTC, anatoliliotych commented on app/controllers/users_controller.rb
> +    params.require(:user).permit(user_profile_attributes: %i(full_name city description avatar avatar_cache))
I don't see where we ignore avatar setting to nil on update

2018-08-21 19:32 UTC, anatoliliotych requested changes

2018-08-21 19:32 UTC, anatoliliotych commented on app/controllers/users_controller.rb
>    def user_profile
make a before action and set instance variable

2018-08-21 19:32 UTC, anatoliliotych commented on app/views/shared/_user_info.html.slim
> +    - unless current_user.user_profile.avatar.url.nil?
try to not repeat the same, move it to model level

2018-08-21 19:32 UTC, anatoliliotych commented on app/views/users/show.html.slim
> +                  | Some info
what is some info?

2018-08-21 19:32 UTC, anatoliliotych commented on app/views/shared/_user_info.html.slim
> +    - unless current_user.user_profile.avatar.url.nil?
where default image is shown?

2018-08-30 12:31 UTC, anatoliliotych requested changes

2018-08-30 12:31 UTC, anatoliliotych commented on app/assets/javascripts/user_profile.js
> +  function readURL(input) {
add empty line

2018-08-30 12:31 UTC, anatoliliotych commented on app/controllers/users/registrations_controller.rb
> +      build_resource({})
check this

2018-08-30 12:31 UTC, anatoliliotych commented on app/views/users/edit.html.slim
> +          = ff.button type: :submit, class: 'btn btn-primary'
waves effect

2018-08-30 12:31 UTC, anatoliliotych commented on app/views/users/show.html.slim
> +
remove empty lines

2018-08-30 13:43 UTC, anatoliliotych approved these changes

2018-08-30 13:43 UTC, merged