As generate links
cybergizer/nicher pull request #55
Opened 2018-08-19 21:05 UTC by SashaShostyr

2018-08-20 08:26 UTC, Vadser commented on spec/controllers/shared_items_controller_spec.rb
> +      end
Look at my tests about rent items controller (DRY)

2018-08-20 14:52 UTC, Vadser approved these changes

2018-08-20 18:41 UTC, anatoliliotych requested changes

2018-08-20 18:41 UTC, anatoliliotych commented on app/assets/javascripts/share_item.js
> +  $(document).on('click','#copyButton', myFunction);
bad naming for function

2018-08-20 18:41 UTC, anatoliliotych commented on app/assets/javascripts/share_item.js
> +  function myFunction() {
bad naming for function

2018-08-20 18:41 UTC, anatoliliotych commented on app/assets/javascripts/share_item.js
> +  $(document).on('click','#copyButton', myFunction);
bad name for selector

2018-08-20 18:41 UTC, anatoliliotych commented on app/assets/javascripts/share_item.js
> +
remove empty line

2018-08-20 18:41 UTC, anatoliliotych commented on app/assets/javascripts/share_item.js
> +    $dialog.addClass("modal-content");
all these logic to style dialog should be move to some function and not just copied.

2018-08-20 18:41 UTC, anatoliliotych commented on app/controllers/items_controller.rb
> +  def index
I thought it was moved to before actions

2018-08-20 18:41 UTC, anatoliliotych commented on app/controllers/shared_items_controller.rb
> +      RentItem.create(item: item, owner: item.user, tenant: current_user)
what is rent_item direction?

2018-08-20 18:41 UTC, anatoliliotych commented on app/controllers/shared_items_controller.rb
> +    current_user.items.find(params[:id])
it will raise exception which is not handled

2018-08-20 18:41 UTC, anatoliliotych commented on app/controllers/shared_items_controller.rb
> +    if valid_params?
what if not valid? why don't we destroy on expiration?

2018-08-20 18:41 UTC, anatoliliotych commented on app/models/shared_item.rb
> +    generate_token if SharedItem.exists?(token: token)
not sure that I follow this line.

2018-08-20 18:41 UTC, anatoliliotych commented on coverage/.resultset.json
> +{
remove this file

2018-08-20 18:41 UTC, anatoliliotych commented on coverage/index.html
> +<!DOCTYPE html>
remove this file

2018-08-20 18:41 UTC, anatoliliotych commented on spec/controllers/shared_items_controller_spec.rb
> +    it 'renders the :index view' do
strange name of example

2018-08-20 18:41 UTC, anatoliliotych commented on spec/controllers/shared_items_controller_spec.rb
> +      user_profile.save
why do we create it here?

2018-08-20 18:41 UTC, anatoliliotych commented on spec/controllers/shared_items_controller_spec.rb
> +      shared_item.save
why it is here?

2018-08-21 08:47 UTC, anatoliliotych requested changes

2018-08-21 08:47 UTC, anatoliliotych commented on app/assets/javascripts/dialog.js
> +function getDialog() {
actually, this method is about styling you dialog, so no need to return dialog, also bad naming.

2018-08-21 08:47 UTC, anatoliliotych commented on app/assets/javascripts/lend_item.js
> +      data: { id: id},
style!

2018-08-21 08:47 UTC, anatoliliotych commented on app/assets/javascripts/share_item.js
> +    var $dialog = getDialog();
no need to return dialog

2018-08-21 08:47 UTC, anatoliliotych commented on app/controllers/shared_items_controller.rb
> +  include SharedItemsHelper
remove helper, and use concerns

2018-08-21 08:47 UTC, anatoliliotych commented on app/controllers/shared_items_controller.rb
> +  rescue StandardError
you can use find_by to return nil

2018-08-21 08:47 UTC, anatoliliotych commented on app/helpers/shared_items_helper.rb
> +    SharedItem.where('expiration < ?', Time.zone.now).destroy_all
you should destroy only the item you work with, otherwise it will hangs user's browser

2018-08-21 08:47 UTC, anatoliliotych commented on app/models/shared_item.rb
> +    self.token = SecureRandom.urlsafe_base64
make it more userfriendly :)

2018-08-21 14:35 UTC, anatoliliotych requested changes

2018-08-21 14:35 UTC, anatoliliotych commented on app/controllers/shared_items_controller.rb
> +    @shared_item && correct_members? && active_token?
no sense to check active_token if you already destroyed shared_item

2018-08-21 14:35 UTC, anatoliliotych commented on app/controllers/shared_items_controller.rb
> +    @shared_item && correct_members? && active_token?
and add test for this case

2018-08-21 19:19 UTC, anatoliliotych requested changes

2018-08-21 19:19 UTC, anatoliliotych commented on spec/controllers/shared_items_controller_spec.rb
> +          shared_item.expiration = Time.zone.now - 1.minute
you can do this in let

2018-08-21 19:19 UTC, anatoliliotych commented on spec/controllers/shared_items_controller_spec.rb
> +          expect{ subject }.to_not change(RentItem,:count)
style

2018-08-21 19:19 UTC, anatoliliotych commented on spec/controllers/shared_items_controller_spec.rb
> +          expect{ subject }.to_not change(RentItem,:count)
style

2018-08-22 10:57 UTC, anatoliliotych requested changes
please, rebase and fix small issues

2018-08-22 10:57 UTC, anatoliliotych commented on app/views/items/index.html.slim
> +        td= link_to nil, class: 'lend_item', data: {id: item.id} do
fix style

2018-08-22 10:57 UTC, anatoliliotych commented on app/views/items/index.html.slim
> +        td= link_to nil, class: 'share_item', data: {id: item.id} do
fix style

2018-08-22 10:57 UTC, anatoliliotych commented on app/views/items/index.html.slim
> +          td= item.item.title
you can delegate title

2018-08-22 12:50 UTC, anatoliliotych approved these changes

2018-08-22 12:50 UTC, merged