Vs add popups
cybergizer/nicher pull request #56
Opened 2018-08-22 14:59 UTC by Vadser

2018-08-22 16:13 UTC, SashaShostyr commented on app/assets/javascripts/categories_popups.js
> +    var $dialog = $(".ui-dialog");
use function addStylesToDialog() from dialog.js

2018-08-22 16:14 UTC, SashaShostyr approved these changes

2018-08-23 08:42 UTC, anatoliliotych requested changes

2018-08-23 08:42 UTC, anatoliliotych commented on app/assets/javascripts/categories_popups.js
> +      $('#error_explanation').addClass('alert alert-warning').html('Please input name for category!').fadeIn().fadeOut(10000);
I see code duplication

2018-08-23 08:42 UTC, anatoliliotych commented on app/assets/javascripts/categories_popups.js
> +        $('#error_explanation').addClass('alert alert-warning').html('Category cannot be a descendant of itself!').fadeIn().fadeOut(10000);
move to function

2018-08-23 08:42 UTC, anatoliliotych commented on app/assets/javascripts/categories_popups.js
> +      data: { id: id},
style

2018-08-23 08:42 UTC, anatoliliotych commented on app/assets/javascripts/categories_popups.js
> +    return name_input.val() != '';
check length

2018-08-23 08:42 UTC, anatoliliotych commented on app/assets/javascripts/categories_popups.js
> +      data: { id: id},
style

2018-08-23 08:42 UTC, anatoliliotych commented on app/assets/javascripts/nishes_popups.js
> +    var $dialog = $(".ui-dialog");
you've missed this!!!

2018-08-23 08:42 UTC, anatoliliotych commented on app/assets/javascripts/nishes_popups.js
> +      $('#error_explanation').addClass('alert alert-warning').html('Please input name for niche!').fadeIn().fadeOut(10000);
move to function

2018-08-23 08:42 UTC, anatoliliotych commented on app/assets/javascripts/nishes_popups.js
> +        $('#error_explanation').addClass('alert alert-warning').html('Niche cannot be a descendant of itself!').fadeIn().fadeOut(10000);
code duplication

2018-08-23 08:42 UTC, anatoliliotych commented on app/assets/javascripts/nishes_popups.js
> +      data: { id: id},
style

2018-08-23 08:42 UTC, anatoliliotych commented on app/assets/javascripts/nishes_popups.js
> +      data: { id: id},
style

2018-08-23 08:42 UTC, anatoliliotych commented on app/views/categories/_form.html.slim
> +    = form_for(@category, :html=>{ :id=>'save_category', :multipart => true}) do |form|
style

2018-08-23 08:42 UTC, anatoliliotych commented on app/views/categories/_form.html.slim
> +        = form.button 'Save', type: :submit, class: 'btn btn-primary waves-effect'
empty line symbol

2018-08-23 08:42 UTC, anatoliliotych commented on app/views/niches/_form.html.slim
> +    = form_for(@niche, :html=>{ :id=>'save_niche', :multipart => true}) do |form|
style

2018-08-23 08:42 UTC, anatoliliotych commented on spec/controllers/categories_controller_spec.rb
> +        expect(response.body).to eq("{\"status\":\"ok\"}")
you can parse body as json and check hashes

2018-08-23 11:18 UTC, anatoliliotych requested changes

2018-08-23 11:18 UTC, anatoliliotych commented on app/assets/javascripts/nishes_popups.js
> +    }else{
spaces

2018-08-23 11:36 UTC, anatoliliotych approved these changes

2018-08-23 11:41 UTC, merged