Add history model
cybergizer/nicher pull request #59
Opened 2018-08-23 12:50 UTC by idealasgas

2018-08-23 13:25 UTC, reedzyy requested changes

2018-08-23 13:25 UTC, reedzyy commented on app/models/rent_item.rb
> +    history.save if item.valid?
Rewrite this method with oneline style

2018-08-23 13:28 UTC, simonovich approved these changes

2018-08-23 13:30 UTC, reedzyy approved these changes

2018-08-23 15:31 UTC, anatoliliotych requested changes

2018-08-23 15:31 UTC, anatoliliotych commented on app/models/item_history.rb
> +  def find
rename

2018-08-23 18:13 UTC, anatoliliotych requested changes

2018-08-23 18:13 UTC, anatoliliotych commented on app/views/items/_history.html.slim
> +    td = history.rent_item.created_at.strftime '%e %b %Y %k:%M'
should be in model/helper not here

2018-08-23 18:13 UTC, anatoliliotych commented on app/views/items/_history.html.slim
> +    td = history.rent_item.created_at.strftime '%e %b %Y %k:%M'
I mean formating

2018-08-23 18:13 UTC, anatoliliotych commented on db/migrate/20180821125245_create_versions.rb
> +      # Known issue in MySQL: fractional second precision
do we use mysql? ) remove this comment

2018-08-24 08:56 UTC, anatoliliotych approved these changes

2018-08-24 09:23 UTC, merged