Lock admin panel
cybergizer/nicher pull request #64
Opened 2018-08-24 10:09 UTC by simonovich

2018-08-29 09:17 UTC, Vadser commented on spec/models/ability_spec.rb
> +      user = User.create(email: 'test@example.com', password: 'password123', password_confirmation: 'password123')
Use factory-bot

2018-08-29 09:17 UTC, Vadser commented on spec/models/ability_spec.rb
> +  describe "as admin" do
Add empty line between sections

2018-08-29 11:20 UTC, anatoliliotych requested changes

2018-08-29 11:20 UTC, anatoliliotych commented on spec/controllers/rails_admin/main_controller_spec.rb
> +    it 'redirects to root path' do
need positive test, that admin can login

2018-08-29 11:20 UTC, anatoliliotych commented on app/models/ability.rb
> +  def initialize(user)
``` 
return unless user && user.admin?
can :access, :rails_admin
can :manage, :all 
```

2018-08-30 12:03 UTC, Vadser approved these changes

2018-08-30 12:15 UTC, anatoliliotych requested changes

2018-08-30 12:15 UTC, anatoliliotych commented on spec/controllers/rails_admin/main_controller_spec.rb
> +#binding.pry
remove

2018-08-30 12:15 UTC, anatoliliotych commented on app/views/categories/index.html.slim
> +p#alert
move this and notice to layout

2018-08-31 08:30 UTC, anatoliliotych approved these changes

2018-08-31 08:31 UTC, merged