Add free items
cybergizer/nicher pull request #69
Opened 2018-08-27 13:16 UTC by idealasgas

2018-08-27 13:20 UTC, Vadser commented on app/views/free_item_requests/filter_notifications.html.slim
> +    = render partial: 'card_of_request', collection: @requests, as: :request
where is empty line! change your editor!

2018-08-27 13:21 UTC, Vadser commented on app/views/items/_form.html.slim
>      = form.collection_select(:category_id, current_user.categories, :id, :name, :include_blank => "Please select")
style!

2018-08-27 13:24 UTC, Vadser commented on spec/factories/free_item_request.rb
> +end
change editor!

2018-08-27 13:25 UTC, Vadser commented on spec/controllers/free_item_requests_controller_spec.rb
> +      expect { subject }.to change(FreeItemRequest, :count).by(0)
useless test

2018-08-27 13:27 UTC, Vadser requested changes
Please look at comments!

2018-08-27 13:58 UTC, anatoliliotych requested changes

2018-08-27 13:58 UTC, anatoliliotych commented on app/controllers/free_item_requests_controller.rb
> +    @item = Item.find_by_id(params[:item_id])
you can move it to before_action and reuse

2018-08-27 13:58 UTC, anatoliliotych commented on app/controllers/free_item_requests_controller.rb
> +    Item.create(title: @item.title, description: @item.description, user: @request.potential_owner, free: false)
false could be default

2018-08-27 13:58 UTC, anatoliliotych commented on app/controllers/welcome_controller.rb
> +    @items = Item.where(free: true).search(params[:search])
make a scope

2018-08-27 13:58 UTC, anatoliliotych commented on app/models/user.rb
> +  has_many :sending_requests, class_name: 'FreeItemRequest', foreign_key: 'potential_owner_id', dependent: :destroy
sending is not describing the actual meaning of this

2018-08-27 13:58 UTC, anatoliliotych commented on app/views/items/_form.html.slim
> +include_blank: "Please select")
why it's here?

2018-08-27 13:58 UTC, anatoliliotych commented on app/views/items/_item_table.html.slim
> +    td free
change text to 'marked as free'

2018-08-27 13:58 UTC, anatoliliotych commented on app/views/items/_item_table.html.slim
> +    td free
and add some icon as present box

2018-08-27 13:58 UTC, anatoliliotych commented on app/views/items/index.html.slim
> +              th free
Capital F

2018-08-27 13:58 UTC, anatoliliotych commented on db/migrate/20180815150048_add_free_to_items.rb
> +    add_column :items, :free, :boolean
set default to false

2018-08-27 13:58 UTC, anatoliliotych commented on spec/controllers/free_item_requests_controller_spec.rb
> +  let(:request) { create(:free_item_request, item: item, actual_owner: item.user, potential_owner: user_potential) }
you can use user_actual instead of item.user

2018-08-27 13:58 UTC, anatoliliotych commented on spec/models/free_item_request_spec.rb
> +  it "is not valid without item" do
what about valid case?

2018-08-27 15:00 UTC, idealasgas commented on app/views/items/_form.html.slim
> +include_blank: "Please select")
@Vadser  commented

2018-08-27 16:23 UTC, Vadser approved these changes

2018-08-27 20:53 UTC, anatoliliotych commented on app/views/items/_form.html.slim
> +include_blank: "Please select")
I mean separate string...

2018-08-27 20:53 UTC, anatoliliotych requested changes
check comments

2018-08-28 05:38 UTC, anatoliliotych requested changes

2018-08-28 05:38 UTC, anatoliliotych commented on app/controllers/free_item_requests_controller.rb
> +  before_action :assign_variable
bad unreadable method name

2018-08-28 05:46 UTC, anatoliliotych requested changes

2018-08-28 05:46 UTC, anatoliliotych commented on app/controllers/free_item_requests_controller.rb
> +  def find_free_item
So usually this method is called set_<bla-bla-bla>.
Also to avoid later problems with nil, I suggest to use find method.

2018-08-28 05:56 UTC, anatoliliotych requested changes

2018-08-28 05:56 UTC, anatoliliotych commented on app/controllers/free_item_requests_controller.rb
> +    @item = Item.find(id: params[:item_id])
no need to pass id: if you are searching by id :)

2018-08-28 05:56 UTC, anatoliliotych commented on app/controllers/free_item_requests_controller.rb
> +    @request = FreeItemRequest.find_by_id(params[:id])
also remove find_by_id

2018-08-28 06:08 UTC, anatoliliotych requested changes

2018-08-28 06:08 UTC, anatoliliotych commented on app/controllers/free_item_requests_controller.rb
> +    @request = FreeItemRequest.find(params[:id])
move it to before action

2018-08-28 09:15 UTC, anatoliliotych approved these changes

2018-08-28 09:15 UTC, merged